<course-streamer 
    :course="{{$course}}" 
    amount="{{$course->getAmount()}}" 
    discountamount="{{$course->getDiscountAmount()}}" 
    classroomamount="{{$course->getClassAmount()}}" 
    discountclassroomamount="{{$course->getClassAmountDiscount()}}" 
    :subject="{{$course->subject}}" 
    :learns="{{$course->learns()->limit(3)->get()}}" 
    :course_path="{{json_encode($course->path())}}"
    :type="{{json_encode($course->type->name)}}"
    :videourl="{{json_encode($course->videopath)}}"
    :lecture_path="{{json_encode($course->firstLectureUrl())}}"
></course-streamer>